name = "puppal-ai-worker"
main = "src/index.ts"
compatibility_date = "2024-06-20"

[vars]
# optional static vars

[observability]
enabled = true

# Bind your secrets before deploy:
# wrangler secret put OPENAI_API_KEY
# wrangler secret put TAVILY_API_KEY


